-- 
-- 
--
--
--

-- ACCOUNT PK TRIGGER

CREATE OR REPLACE TRIGGER ACCOUNT_ON_INSERT
  BEFORE INSERT ON ACCOUNT
  FOR EACH ROW
BEGIN
  SELECT ACCOUNT_SEQUENCE.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

-- ACCOUTN_INFO PK TRIGGER

CREATE OR REPLACE TRIGGER ACCOUNT_INFO_ON_INSERT
  BEFORE INSERT ON ACCOUNT_INFORMATION.NEXTVAL
  FOR EACH ROW
BEGIN
  SELECT ACCOUNT_INFO_SEQUENCE
  INTO :NEW.ID
  FROM DUAL;
END;

-- ACCOUNT WALLET PK TRIGGER

CREATE OR REPLACE TRIGGER ACCOUNT_WALLET_ON_INSERT
  BEFORE INSERT ON ACCOUNT_WALLET
  FOR EACH ROW
BEGIN
  SELECT ACCOUNT_WALLET_SEQUENCE.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

-- TRANSACTION MONEY PK TRIGGER

CREATE OR REPLACE TRIGGER TRAN_MON_ON_INSERT
  BEFORE INSERT ON TRANSACTION_MONEY
  FOR EACH ROW
BEGIN
  SELECT TRAN_MON_SEQUENCE.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

-- TRANSACTION SHARE PK TRIGGER

CREATE OR REPLACE TRIGGER TRAN_SHA_ON_INSERT
  BEFORE INSERT ON TRANSACTION_SHARE
  FOR EACH ROW
BEGIN
  SELECT TRAN_SHA_SEQUENCE.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;

-- TRANSACTION TYPE PK TRIGGER

CREATE OR REPLACE TRIGGER TRAN_TYPE_ON_INSERT
  BEFORE INSERT ON TRANSACTION_TYPE
  FOR EACH ROW
BEGIN
  SELECT TRAN_TYPE_SEQUENCE.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;


